name: deftrello
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - requests
  - python-dotenv
  - click
  - pandas
  - pytest
  - pip
  - pip:
      - py-trello
      - anthropic
